language:
  ruby

rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.0'

matrix:
  fast_finish:
    true

install: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ruby gcc ruby-dev rake make -y

script:
  - bundle exec rake install
  - bundle exec rake spec

